import os
import pandas as pd
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors

# Paths
TICKETS_PATH = "logs/soc_tickets.csv"
FLOW_FINAL_PATH = "logs/live_flows_final.csv"
OUTPUT_PATH = "reports/SOC_Summary_Report.pdf"

def generate_report():
    os.makedirs("reports", exist_ok=True)
    
    doc = SimpleDocTemplate(OUTPUT_PATH, pagesize=letter)
    styles = getSampleStyleSheet()
    elements = []

    # Title
    title_style = ParagraphStyle(
        'TitleStyle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.hexColor("#1f77b4"),
        alignment=1, # Center
        spaceAfter=20
    )
    elements.append(Paragraph("IoT IDS SOC Summary Report", title_style))
    elements.append(Paragraph(f"Generated on: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", styles['Normal']))
    elements.append(Spacer(1, 20))

    # Executive Summary
    elements.append(Paragraph("1. Executive Summary", styles['Heading2']))
    
    total_tickets = 0
    high_severity_count = 0
    if os.path.exists(TICKETS_PATH):
        tickets = pd.read_csv(TICKETS_PATH)
        total_tickets = len(tickets)
        high_severity_count = len(tickets[tickets['severity'].isin(['HIGH', 'CRITICAL'])])
    
    summary_text = f"This report provides a summary of the Intrusion Detection System (IDS) status and Security Operations Center (SOC) activity. " \
                   f"A total of {total_tickets} security tickets have been generated, with {high_severity_count} flagged as HIGH or CRITICAL severity."
    elements.append(Paragraph(summary_text, styles['Normal']))
    elements.append(Spacer(1, 20))

    # Recent High Severity Incidents
    elements.append(Paragraph("2. Recent High-Severity Incidents", styles['Heading2']))
    
    if os.path.exists(TICKETS_PATH):
        tickets = pd.read_csv(TICKETS_PATH)
        high_tickets = tickets[tickets['severity'].isin(['HIGH', 'CRITICAL'])].tail(10)
        
        if not high_tickets.empty:
            data = [["Ticket ID", "Timestamp", "Attacker IP", "Victim IP", "Severity"]]
            for _, row in high_tickets.iterrows():
                data.append([
                    str(row.get('ticket_id', 'N/A')),
                    str(row.get('timestamp', 'N/A'))[:19],
                    str(row.get('attacker_ip', 'N/A')),
                    str(row.get('victim_ip', 'N/A')),
                    str(row.get('severity', 'N/A'))
                ])
            
            t = Table(data)
            t.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.hexColor("#1f77b4")),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 12),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
                ('GRID', (0, 0), (-1, -1), 1, colors.black)
            ]))
            elements.append(t)
        else:
            elements.append(Paragraph("No high-severity incidents recorded.", styles['Normal']))
    else:
        elements.append(Paragraph("Ticket log file not found.", styles['Normal']))

    elements.append(Spacer(1, 20))

    # Network Status
    elements.append(Paragraph("3. Network Traffic Status", styles['Heading2']))
    if os.path.exists(FLOW_FINAL_PATH):
        flows = pd.read_csv(FLOW_FINAL_PATH)
        total_flows = len(flows)
        elements.append(Paragraph(f"Total analyzed network flows: {total_flows}", styles['Normal']))
    else:
        elements.append(Paragraph("Flow log file not found.", styles['Normal']))

    # Footer
    elements.append(Spacer(1, 40))
    elements.append(Paragraph("Note: This report is automatically generated by the IoT IDS ML Dashboard SOC Engine.", styles['Italic']))

    doc.build(elements)
    print(f"Report generated at {OUTPUT_PATH}")

if __name__ == "__main__":
    generate_report()
